version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - libegl1-mesa
    - libgl1-mesa-dri
    - libxcb-xfixes0-dev
    - mesa-vulkan-drivers
    - libglfw3
    - pandoc
  jobs:
    pre_install:
      - pip install git+https://github.com/pygfx/pygfx.git@main

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
