version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - libegl1-mesa
    - libgl1-mesa-dri
    - libxcb-xfixes0-dev
    - mesa-vulkan-drivers
    - libglfw3

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
