"""
Polygon animation
=================

Polygon animation example that changes the polygon data. Random points are generated by sampling from a
2D gaussian and a polygon is updated to visualize a convex hull for the sampled points.

"""

# test_example = false
# sphinx_gallery_pygfx_docs = 'animate 8s'

import numpy as np
from scipy.spatial import ConvexHull
import fastplotlib as fpl
from time import perf_counter


def points_to_hull(points) -> np.ndarray:
    hull = ConvexHull(points, qhull_options='Qs')
    return points[hull.vertices]


figure = fpl.Figure(size=(700, 560))

mu = (0, 0)
cov = np.array([[1, 0], [0, 1]])

# sample points from a 2d gaussian
samples = np.random.multivariate_normal(mu, cov, size=20)

# add the convex hull as a polygon
polygon = figure[0, 0].add_polygon(points_to_hull(samples), colors="cyan")
# add the sampled points
scatter = figure[0, 0].add_scatter(samples, sizes=8, colors="magenta")

t = perf_counter()
def animate():
    global t
    # generate new data every ~0.2 seconds
    if perf_counter() - t < 0.2:
        return

    # generate new samples
    samples = np.random.multivariate_normal(mu, cov, size=20)

    # set new scatter data
    scatter.data[:, :-1] = samples
    # set convex hull with new polygon vertices
    polygon.data = points_to_hull(samples)

    t = perf_counter()


figure.show()
figure[0, 0].camera.width = 8
figure[0, 0].camera.height = 8

figure.add_animations(animate)


# NOTE: fpl.loop.run() should not be used for interactive sessions
# See the "JupyterLab and IPython" section in the user guide
if __name__ == "__main__":
    print(__doc__)
    fpl.loop.run()
