# Form implementation generated from reading ui file 'qtoolbar.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QToolbar(object):
    def setupUi(self, QToolbar):
        QToolbar.setObjectName("QToolbar")
        QToolbar.resize(638, 48)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(QToolbar)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.auto_scale_button = QtWidgets.QPushButton(parent=QToolbar)
        self.auto_scale_button.setObjectName("auto_scale_button")
        self.horizontalLayout.addWidget(self.auto_scale_button)
        self.center_button = QtWidgets.QPushButton(parent=QToolbar)
        self.center_button.setObjectName("center_button")
        self.horizontalLayout.addWidget(self.center_button)
        self.panzoom_button = QtWidgets.QPushButton(parent=QToolbar)
        self.panzoom_button.setCheckable(True)
        self.panzoom_button.setObjectName("panzoom_button")
        self.horizontalLayout.addWidget(self.panzoom_button)
        self.maintain_aspect_button = QtWidgets.QPushButton(parent=QToolbar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maintain_aspect_button.setFont(font)
        self.maintain_aspect_button.setCheckable(True)
        self.maintain_aspect_button.setObjectName("maintain_aspect_button")
        self.horizontalLayout.addWidget(self.maintain_aspect_button)
        self.y_direction_button = QtWidgets.QPushButton(parent=QToolbar)
        self.y_direction_button.setObjectName("y_direction_button")
        self.horizontalLayout.addWidget(self.y_direction_button)
        self.add_polygon_button = QtWidgets.QPushButton(parent=QToolbar)
        self.add_polygon_button.setObjectName("add_polygon_button")
        self.horizontalLayout.addWidget(self.add_polygon_button)
        self.record_button = QtWidgets.QPushButton(parent=QToolbar)
        self.record_button.setCheckable(True)
        self.record_button.setObjectName("record_button")
        self.horizontalLayout.addWidget(self.record_button)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(QToolbar)
        QtCore.QMetaObject.connectSlotsByName(QToolbar)

    def retranslateUi(self, QToolbar):
        _translate = QtCore.QCoreApplication.translate
        QToolbar.setWindowTitle(_translate("QToolbar", "Form"))
        self.auto_scale_button.setText(_translate("QToolbar", "autoscale"))
        self.center_button.setText(_translate("QToolbar", "center"))
        self.panzoom_button.setText(_translate("QToolbar", "panzoom"))
        self.maintain_aspect_button.setText(_translate("QToolbar", "1:1"))
        self.y_direction_button.setText(_translate("QToolbar", "^"))
        self.add_polygon_button.setText(_translate("QToolbar", "polygon"))
        self.record_button.setText(_translate("QToolbar", "record"))
