from collections.abc import Callable
from typing import Protocol, runtime_checkable


@runtime_checkable
class SelectorProtocol(Protocol):
    @property
    def selection(self): ...

    @selection.setter
    def selection(self, new): ...

    def add_event_handler(self, handler: Callable): ...

    def remove_event_handler(self, handler: Callable): ...


@runtime_checkable
class MultiSelectorProtocol(SelectorProtocol, Protocol):
    def append(self, item): ...

    def remove(self, item): ...

    def clear(self): ...

    def __len__(self): ...

    def __contains__(self, item): ...

    def __iter__(self): ...
