name: Docs
on: [push, release]

jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install llvmpipe and lavapipe for offscreen canvas
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install --no-install-recommends -y ffmpeg libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers git-lfs
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          # remove pygfx from install_requires, we install using pygfx@main
          sed -i "/pygfx/d" ./setup.py
          pip install git+https://github.com/pygfx/pygfx.git@main
          pip install -e ".["docs"]"
      - name: Show wgpu backend
        run:
          python -c "from examples.tests.testutils import wgpu_backend; print(wgpu_backend)"
      - name: make gallery
        run: |
          RTD_BUILD=1 FETCH_ARTIFACT=0 sphinx-build -b dummy docs/source/ /tmp/

      - uses: actions/upload-artifact@v4
        with:
          name: gallery-${{ github.sha }}
          path: docs/source/_gallery

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
