name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Get PR Number
      id: pr
      run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v4
    - name: Build HTML
      uses: ammaraskar/sphinx-action@8.0.2
      with:
        pre-build-command: |
          apt-get update -y -qq
          apt-get install --no-install-recommends -y build-essential
          apt-get install --no-install-recommends -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers git-lfs
          # fetch lfs files
          git lfs fetch --all
          git lfs pull
          # remove pygfx from install_requires, we install using pygfx@main
          sed -i "/pygfx/d" ./setup.py
          pip install git+https://github.com/pygfx/pygfx.git@main
          pip install -e ".[notebook,docs,tests]"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.6.8
      # if: github.ref == 'refs/heads/main'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        token: ${{ secrets.PUSH_DOCS }}
        repository-name: fastplotlib/doc-builds
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/build/html # The folder the action should deploy.
        target-folder: versions/${{ steps.pr.outputs.pull_request_number }}
        clean: true # Automatically remove deleted files from the deploy branch
        CLEAN_EXCLUDE: '["versions"]'
