name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: install python
      uses: actions/setup-python@v4
      with:
          python-version: 3.11
    - name: install deps
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install --no-install-recommends -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers git-lfs
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        # remove pygfx from install_requires, we install using pygfx@main
        sed -i "/pygfx/d" ./setup.py
        pip install git+https://github.com/pygfx/pygfx.git@main
        pip install -e ".[notebook,docs,tests]"
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
