name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build HTML
      uses: ammaraskar/sphinx-action@8.0.2
      with:
        pre-build-command: |
          apt-get update -y -qq
          apt-get install --no-install-recommends -y build-essential
          apt-get install --no-install-recommends -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers git-lfs
          # remove pygfx from install_requires, we install using pygfx@main
          sed -i "/pygfx/d" ./setup.py
          pip install git+https://github.com/pygfx/pygfx.git@main
          pip install -e ".[notebook,docs,tests]"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.6.8
      # if: github.ref == 'refs/heads/main'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/build/html # The folder the action should deploy.
        TARGET_FOLDER: ${{ github.event.number }}
        CLEAN: true # Automatically remove deleted files from the deploy branch
        #CLEAN_EXCLUDE: '["version"]'
